# Generated by Django 4.2.7 on 2023-11-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
