# Generated by Django 4.2.7 on 2023-12-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_wallet_change',
            field=models.BooleanField(default=False),
        ),
    ]
