# Generated by Django 4.2.7 on 2023-12-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_is_wallet_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_identification/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_identification/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('id_card', 'ID Card'), ('passport', 'Passport'), ('driver_license', "Driver's License")], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='selfie_with_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_identification/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
